# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KLItJqKbiivFZ9j7r00Xf7l3U3BNK6iE
"""

import sys

for qq in sys.stdin:
  if qq=="QUIT":
    print("Bye!", file=sys.stderr)
    break
uppers=sys.stdin.upper()
sys.stdout.write(uppers)